### ISSUE TITLE
Laravel Vapor support

### ISSUE THREAD

**Issue by jerguslejko** [laravel/tinker#106]
Right now, _tinker_ can't be used inside Laravel Vapor because in order to run _psysh_ (which tinker uses), it needs to be able to create a _runtime directory_ (which defaults to `~/.config/psysh` -- this is not available inside an AWS Lambda). See the `runtimeDir` option @ https://github.com/bobthecow/psysh/wiki/Config-options. 

However, this directory path can be changed by setting the `XDG_CONFIG_HOME` variable.

Not sure if this should be a _tinker_ feature or a Vapor feature. 

Anyway, once this is resolved, people can use `php artisan tinker --execute "dump(config('queue'))"` or whatever inside their vapor lambdas

**Comment by themsaid** [comment]
Hey,

You can try that by setting a XDG_CONFIG_HOME environment variable on Vapor and see if it works. Contact us on vapor@laravel.com if that works and we'll see if it's safe to make it possible to configure it in Vapor by default.

**Comment by bsormagec** [comment]
@themsaid XDG_CONFIG_HOME=/tmp works Lambda has 500MB temp dir on "/tmp" directory and it worked on me i just wanna inform you about this 👍🏼
