### ISSUE TITLE
Error Handling in Tinker

### ISSUE THREAD

**Issue by PaulBehrendtVentoro** [laravel/tinker#107]
- Tinker Version: v2.4.0
- Laravel Version: v7.12.0
- PHP Version: v7.4.7
- Database Driver & Version: PDO Driver for MySQL (?)

### Description:
Error handler for Tinker is taken from psy/psysh:v0.10.4, instead using Laravel Framework's "src/Illuminate/Foundation/Bootstrap/HandleExceptions.php".
This leads to me not noticing Bugs, that will throw an ErrorException in Production :laughing: 
Did not look this up, but i think that used to be different.

### Steps To Reproduce:
>>> trigger_error('notice', E_USER_NOTICE);

**Comment by driesvints** [comment]
This can easily be documented. Feel free to send in a pr to the docs! Thanks.
