### ISSUE TITLE
PHP Warning after logging in using Auth in Tinker

### ISSUE THREAD

**Issue by micksp** [laravel/tinker#111]
- Tinker Version: 2.4.2
- Laravel Version: 7.25.0
- PHP Version: 7.2.33
- Database Driver & Version: Mysql 8.0.21-0ubuntu0.20.04.4

### Description:
when I login using Auth::login in Tinker, I get a warning: 
```
PHP Warning:  unlink({path}/storage/framework/sessions/3p6YqECrq3EAMP4Hdz2X5IBdw4cfRG30bLNpY9z4): 
No such file or directory in {path}/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 220
```
After the warning, everything works, I can use my usual queries that need a logged-in user. So this is not a high prio thing. 
Seems there is no session present to be removed. 

### Steps To Reproduce:
1. start tinker `artisan tinker`
1. login user
```
$u = User::find(1);
Auth::login($u);
```

**Comment by driesvints** [comment]
I don't think keeping track of session state through Tinker makes sense.
