### ISSUE TITLE
Use isset() method

### ISSUE THREAD

**Issue by tdt0412** [laravel/tinker#115]
`isset(1);`
PHP Parse error: Syntax error, unexpected T_LNUMBER on line 1

**Comment by GrahamCampbell** [comment]
Please open an issue upstream.

**Comment by GrahamCampbell** [comment]
https://github.com/bobthecow/psysh/issues

**Comment by bobthecow** [comment]
This is … what PHP does when you call `isset()` on a literal number?

https://3v4l.org/SOsHd

**Comment by GrahamCampbell** [comment]
Is the complaint that psysh doesn't catch that this is not allowed, and provide a nice error message, like it does for some other syntax errors?

**Comment by bobthecow** [comment]
maybe? ¯\_(ツ)_/¯ 

I just pushed a change that adds a code cleaner for `isset()` ☝️

**Comment by driesvints** [comment]
Nice. Thanks @bobthecow!
