### ISSUE TITLE
Using --execute option produces no output

### ISSUE THREAD

**Issue by bosunski** [laravel/tinker#118]
- Tinker Version: v2.5.0
- Laravel Version: 8.15.0
- PHP Version: 7.4.12 
- Database Driver & Version: 

### Description:
The `execute` option seems to not be working when used. It doesn't give an output when you use the option.

### Steps To Reproduce:
Run `php artisan tinker --execute="[1, 2, 3, 4]"`

**Comment by driesvints** [comment]
It's silent:

```bash
main $ php artisan tinker --execute="echo 'test'" 
test<aside>⏎</aside>
```

**Comment by bosunski** [comment]
Thanks @driesvints !
