### ISSUE TITLE
How to use japanese character in laravel/tinker?

### ISSUE THREAD

**Issue by onirusama** [laravel/tinker#12]
In my ubuntu i can input japanese character in my terminal. But when i try insert some japanese character with tinker it's look like tinker not support it. I mean when i try type some japanese example 'わたし' (in japanese input we need enter after type some word, because by default we get some suggestion word, so we hit enter to select the word). But after enter no word shown in terminal. Any configuration to fix this? Thanks. Sory for bad english.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. I'm not sure. Try asking on the psysh repo. They're likely to be able to help. :)

---

https://github.com/bobthecow/psysh
