### ISSUE TITLE
After update php version to 7.4.0 , php artisan tinker command got error

### ISSUE THREAD

**Issue by lzzarlin** [laravel/tinker#125]
- Tinker Version: "laravel/tinker": "^2.5",
- Laravel Version: 8.*
- PHP Version: 7.4.0beta4
- Database Driver & Version: mysql 5.7.27

### Description:
error info:
Psy Shell v0.10.5 (PHP 7.4.0beta4 — cli) by Justin Hileman
ErrorException with message 'Unbinding $this of closure is deprecated'

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by bobthecow** [comment]
This was a bug in the PHP 7.4 betas. Updating to a stable release will resolve it.

https://github.com/bobthecow/psysh/issues/567
