### ISSUE TITLE
How is idea of making laravel tinker that detect the updates in code instantly?

### ISSUE THREAD

**Issue by GunarajKhatri** [laravel/tinker#128]
If we are in tinker and somehow if we update some part of codes and try to execute again through it then it won't detect our updates so we need to close and open it again to make it detect which seems painful if we are writing codes and needs to be update somehow.
Thank you !!

**Comment by bobthecow** [comment]
See the discussion in https://github.com/bobthecow/psysh/issues/416

**Comment by GunarajKhatri** [comment]
seems this feature is not discussed here !!

**Comment by bobthecow** [comment]
That entire issue is a discussion of this feature?
