### ISSUE TITLE
Add ability to refresh Tinker session from within Tinker?

### ISSUE THREAD

**Issue by exzachlyvv** [laravel/tinker#130]
It would be nice to be able to refresh the Tinker session from within Tinker. Is there a reason this feature does not exist?

I'd be happy to help implement it :)

**Comment by driesvints** [comment]
No plans for this right now, sorry.

**Comment by bobthecow** [comment]
For more info than you cared to know on the state of this, see https://github.com/bobthecow/psysh/issues/416 🙂
