### ISSUE TITLE
Add migrate:install to white listed commands

### ISSUE THREAD

**Issue by michaelhume** [laravel/tinker#136]
Hi, 

Since the `migrate` command depends on `migrate:install` in order to [prepare the database](https://github.com/laravel/framework/blob/78637dcc784e8c85e08490d47098cd7531dcaa81/src/Illuminate/Database/Console/Migrations/MigrateCommand.php#L107) when first run, if running code that executes a call to `migrate` within tinker (on a fresh db) a `Symfony/Component/Console/Exception/NamespaceNotFoundException with message 'There are no commands defined in the "migrate" namespace.'` is the result. 

Adding `migrate:install` to the [whitelisted commands](https://github.com/laravel/tinker/blob/a36c207030c5df493f2f7834af93cc2fb2887276/src/Console/TinkerCommand.php#L22) resolves this. 

N.B. Adding ` \Illuminate\Database\Console\Migrations\InstallCommand::class` to config/tinker.php results in a BindingResolutionException: `Target [Illuminate\Database\Migrations\MigrationRepositoryInterface] is not instantiable while building [Illuminate\Database\Console\Migrations\InstallCommand].`

Thanks for all you do!

**Comment by driesvints** [comment]
I don't think this belongs in that list but you can always attempt a pr to see if Taylor would accept it. Thanks
