### ISSUE TITLE
assert always returns true

### ISSUE THREAD

**Issue by khalyomede** [laravel/tinker#138]
- Tinker Version: 1.0.10
- Laravel Version: 6.18.31
- PHP Version: 7.4.3
- Database Driver & Version: 5.7.29

### Description:

`assert()` always returns true.

### Steps To Reproduce:

Run this code, it always returns true

```bash
/var/www/html# php artisan tinker
Psy Shell v0.9.12 (PHP 7.4.3 — cli) by Justin Hileman
>>> $test = null;
=> null
>>> assert($test instanceof PDO);
=> true
>>>
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by bobthecow** [comment]
Probably https://www.php.net/manual/en/ini.core.php#ini.zend.assertions
