### ISSUE TITLE
Issue registering StorageLinkCommand

### ISSUE THREAD

**Issue by michaelhume** [laravel/tinker#143]
- Tinker Version: v0.11.2
- Laravel Version: 9.4.1
- PHP Version: 8.1.3

### Description:
I have recently encountered a problem attempting to bind the StorageLinkCommand into tinker. 

This was working, but I've been using Tinkerwell for a while now (which has no issue) so I'm not exactly sure at what point it stopped working, but I now get a `TypeError` when attempting to start tinker. 

```bash
  Psy\Shell::add(): Argument #1 ($command) must be of type Symfony\Component\Console\Command\Command, null given, called in /path/to/my/code/vendor/symfony/console/Application.php on line 478
```

In config/tinker.php I have:

```php
'commands' => [
        \Illuminate\Foundation\Console\StorageLinkCommand::class,
    ],
```

If I remove this - all is well. 

In [TinkerCommand.php](https://github.com/laravel/tinker/blob/31d94864d1e6e68f52a08bc8742600b66908154e/src/Console/TinkerCommand.php#L105) the command is failing to resolve from the app

```php
foreach ($config->get('tinker.commands', []) as $command) {
            $commands[] = $this->getApplication()->resolve($command);   // <-- this is returning null
        }
```

Any idea what might be happening here?

### Steps To Reproduce:
Add the following to config/tinker.php and try to start tinker

```php
'commands' => [
        \Illuminate\Foundation\Console\StorageLinkCommand::class,
    ],
```

**Comment by driesvints** [comment]
Actually, I now notice that none of the artisan commands work anymore within Tinker with Laravel 9. I'll investigate. Thanks

**Comment by driesvints** [comment]
Fixed with https://github.com/laravel/tinker/pull/144
