### ISSUE TITLE
PHP Error: Call to a member function make() on null

### ISSUE THREAD

**Issue by Brenneisen** [laravel/tinker#145]
- Tinker Version: 2.7.1
- Laravel Version: 9.5.1
- PHP Version: 8.1.3
- Database Driver & Version:

### Description:

I get the following error when running custom commands with `laravel/tinker 2.7.1` and `laravel/framework 9.5.1`. With `2.7.0` it still works.

`PHP Error: Call to a member function make() on null in /home/vagrant/workspace/Falcon/backend/vendor/laravel/framework/src/Illuminate/Console/Command.php on line 116`

**Comment by driesvints** [comment]
I'll check in on this tomorrow but it feels odd that the Laravel application isn't set for your command.

**Comment by Brenneisen** [comment]
Seems to be related to https://github.com/laravel/tinker/pull/144.

**Comment by driesvints** [comment]
@Brenneisen everything works fine for me on these versions. I'll need specific instructions on how to reproduce this.

**Comment by Brenneisen** [comment]
@driesvints Here are the steps to reproduce this.

<img width="575" alt="Bildschirmfoto 2022-03-17 um 12 01 00" src="https://user-images.githubusercontent.com/5833477/158796729-64f3c44a-53f3-4f29-a2f6-64df3da6e998.png">

<img width="278" alt="Bildschirmfoto 2022-03-17 um 12 03 05" src="https://user-images.githubusercontent.com/5833477/158796912-fd5109f6-99e8-484a-8d50-b3949577575c.png">

<img width="462" alt="Bildschirmfoto 2022-03-17 um 12 06 09" src="https://user-images.githubusercontent.com/5833477/158797025-4d4e3bdb-8e77-4f97-bedd-a48c6e10ea5f.png">

<img width="515" alt="Bildschirmfoto 2022-03-17 um 12 13 22" src="https://user-images.githubusercontent.com/5833477/158797278-8c66c621-a849-4451-bcd3-422947e45b70.png">

<img width="1210" alt="Bildschirmfoto 2022-03-17 um 12 08 58" src="https://user-images.githubusercontent.com/5833477/158797057-524111dc-c59e-4006-aedd-c8216db5c37f.png">

**Comment by driesvints** [comment]
Thank you, I can now see the issue. I've sent in a fix here: https://github.com/laravel/tinker/pull/146
