### ISSUE TITLE
stream_wrapper_register(): Protocol hoa:// is already defined in psy/psysh/src/Readline/Hoa/ProtocolWrapper.php:473

### ISSUE THREAD

**Issue by TAGHREEDAA** [laravel/tinker#150]
- Tinker Version: ^2.0
- Laravel Version: ^8.0
- PHP Version: ^7.4
- Database Driver & Version: mysql 8.0.21 - Homebrew

### Description:
When using laravel tinker extension with PHPStorm editor I got this issue 

local.ERROR: Uncaught ErrorException: stream_wrapper_register(): Protocol hoa:// is already defined. in 
/vendor/psy/psysh/src/Readline/Hoa/ProtocolWrapper.php:473

#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'stream_wrapper_...', '/Users/taghreed...', 473, Array)
#1 vendor/psy/psysh/src/Readline/Hoa/ProtocolWrapper.php(473): stream_wrapper_register('hoa', 'Psy\\Readline\\Ho...')
#2 vendor/composer/ClassLoader.php(444): include('/Users/taghreed...')
#3 vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Users/taghreed...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('Psy\\Readline\\Ho...')
#5 [internal function]: spl_autoload_call('Psy\\Readline\\Ho...')
#6 vendor/psy/psysh/src/Readline/Userland.php(83): {"exception":"[object] 

### Steps To Reproduce:
Use psy/psysh in your project composer

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
