### ISSUE TITLE
The destructor is not executed

### ISSUE THREAD

**Issue by martio** [laravel/tinker#157]
- Tinker Version: 2.7.3
- Laravel Version: 9.45.1
- PHP Version: 8.1.13
- Database Driver & Version: none

### Description:

Recently I noticed that the class destructor is not executed. I checked on an old version of Tinker and it's OK.

### Steps To Reproduce:

<img width="507" alt="Zrzut ekranu 2022-12-30 o 11 36 43" src="https://user-images.githubusercontent.com/133636/210061163-43a89d7a-617b-4e0e-8786-21c0bcb47248.png">

**Comment by driesvints** [comment]
Tinker is a long running process. A destructor isn't executed here.

**Comment by bobthecow** [comment]
The destructor will be executed the next time you type anything:

<img width="842" alt="Screenshot 2022-12-30 at 11 44 29 AM" src="https://user-images.githubusercontent.com/53660/210093747-66835b09-1691-47f3-8b46-eefbb5fcc6b9.png">

[PsySH keeps a reference to the most recent return value around in the `$_` magic variable](https://github.com/bobthecow/psysh/wiki/Magic-variables), so you've gotta do something to clear that out before the destructor will be called:

<img width="842" alt="Screenshot 2022-12-30 at 11 45 53 AM" src="https://user-images.githubusercontent.com/53660/210093827-97dd20dc-0dd7-4fc1-a0fa-9d791c33ede7.png">

You'd have similar issues with the `$_e` magic variable.
