### ISSUE TITLE
Output cleared and missing colors after upgrading to Laravel 9

### ISSUE THREAD

**Issue by avivais** [laravel/tinker#164]
### Tinker Version

2.8.1

### Laravel Version

9.52.7

### PHP Version

8.1.17

### Description

Since we upgraded to Laravel 9, tinker lost colors and seems to be padding all output (Both probably related):
![Screenshot 2023-05-16 at 16 11 04](https://github.com/laravel/tinker/assets/1503623/ee602bce-d9f0-41c1-8252-0df462f14928)
![Screenshot 2023-05-16 at 16 11 21](https://github.com/laravel/tinker/assets/1503623/4fe65855-1941-41bd-9d5e-063c5f3eaf26)

### Steps To Reproduce

`$ php artisan tinker`
`> dump('hi')`

**Comment by driesvints** [comment]
Seems to be working fine for me.

<img width="813" alt="Screenshot 2023-05-16 at 16 26 32" src="https://github.com/laravel/tinker/assets/594614/892f0443-1fa3-4495-9b51-ceccaa3e41d9">

**Comment by andya-pixelbeard** [comment]
Also experienced this issue running the same Laravel version and laravel/tinker package version

**Comment by bobthecow** [comment]
Can you run `\Psy\info()` and paste the output?
