### ISSUE TITLE
Hardcoded path to vendor/composer in Console/TinkerCommand

### ISSUE THREAD

**Issue by DariusIII** [laravel/tinker#25]
Having hardcoded path prevents customizing folder structure, because tinker stops working if you change vendor_dir in composer.json file.

https://github.com/laravel/tinker/blob/master/src/Console/TinkerCommand.php#L57

Release 1.0.1 did not have this issue.

**Comment by GrahamCampbell** [comment]
We'd be up for a PR to fix this. :+1:

**Comment by dinhanhhuy** [comment]
same here, any 1 come up with a new pull request?

**Comment by DariusIII** [comment]
I have created a PR: https://github.com/laravel/tinker/pull/26

**Comment by DariusIII** [comment]
@taylorotwell closed the PR, so it is how it is.
