### ISSUE TITLE
Message could use improvement to save developers time

### ISSUE THREAD

**Issue by leelbrown** [laravel/tinker#27]
I was tinkering with a new project I am working on (trying to verify relationships work - debugging one that doesnt).  I closed the tinker window, renamed a database table.  Upon returning, I have had a few cryptic messages such as the following:

----------------------

`| ~/Laravel/ob-jobs @ Lees-MBP (leebrown) 
| => php artisan tinker
                                                                              
  [Symfony\Component\Debug\Exception\FatalThrowableError]                     
  Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')'  
                                                                              
`
---------

It would really be nice if the error handler could indicate in which file the error occurred.  Might save (less experienced people like me) a lot of hunting...

**Comment by GrahamCampbell** [comment]
Thanks for the report, but this isn't a bug in Laravel tinker itself.
