### ISSUE TITLE
Unexpected? behaviour dispatching to queues.

### ISSUE THREAD

**Issue by liefie** [laravel/tinker#28]
Found some unexpected behaviour when dispatching jobs within tinker - namely jobs are dispatched the loop after you call them.

 I don’t know enough about queues (or tinker!) to know why.

```➜  dashboard git:(develop) ✗ art tinker
Psy Shell v0.8.11 (PHP 7.1.8 — cli) by Justin Hileman
>>> App\Jobs\TestJob::dispatch(1);
=> Illuminate\Foundation\Bus\PendingDispatch {#831}
>>> App\Jobs\ TestJob::dispatch(2);
string(23) "TestJob(1) actually queued"
=> Illuminate\Foundation\Bus\PendingDispatch {#825}
>>> App\Jobs\ TestJob::dispatch(3);
string(23) "TestJob(2) actually queued"
=> Illuminate\Foundation\Bus\PendingDispatch {#834}
>>> App\Jobs\ TestJob::dispatch(4);
string(23) "TestJob(3) actually queued"
=> Illuminate\Foundation\Bus\PendingDispatch {#846}
>>> $nop = true
=> true
>>> 3
=> 3
>>> sleep(1)
=> 0
>>> exit
string(23) "TestJob(4) actually queued"
Exit:  Goodbye.
```

The dispatching of jobs is delayed, and if you `exit` from tinker right after a dispatch() then the job (usually!) isn’t dispatched.  (except it was in the test above!)

It's the same in Laravel 5.4 and 5.5.

**Comment by GrahamCampbell** [comment]
This is because of the dispatch helper using garbage collection to dispatch. Call `Bus::dispatch()` instead to avoid this.

**Comment by GrahamCampbell** [comment]
(or whatever the name of the facade is, if one exists, you know what I mean)

**Comment by taylorotwell** [comment]
Yeah dispatch the job using Bus::dispatch or Queue::push

**Comment by gabrielalack** [comment]
I feel like there should be a warning about this on the doc page for queues. Would have saved me some time before having to come looking for this!

**Comment by matthewhaworth** [comment]
I've just come across this, wasted many hours getting quite confused!

**Comment by robclancy** [comment]
For people coming here you can just destruct the object you get.

```php
App\Jobs\SendTasksDigest::dispatch(App\User::find(5))->__destruct();
```

**Comment by mattbucci** [comment]
@robclancy I find this approach causes the job to be dispatched twice

**Comment by simik-ru** [comment]
> 
> 
> @robclancy I find the approach
> `App\Jobs\SendTasksDigest::dispatch(App\User::find(5))->__destruct();`
> causes the job to be dispatched twice

Try the following instread:
`app(\Illuminate\Contracts\Bus\Dispatcher::class)->dispatch(new \App\Jobs\SendNotifications());`

**Comment by louisitvn** [comment]
It is really annoying! Can anyone help explain why it was intended like that? How about adding a f

> This is because of the dispatch helper using garbage collection to dispatch. Call `Bus::dispatch()` instead to avoid this.

Can anyone explain why it was intended like that? It is really annoying.
