### ISSUE TITLE
Change Config Path psysh

### ISSUE THREAD

**Issue by adecma** [laravel/tinker#33]
Hy,
I have problem after run tinker in my server. Error like this 
```
 [ErrorException]
  Writing to /home/117544.cloudwaysapps.com/gykhzmvvcd/.config/psysh is not a
  llowed.
```

Can not create config folder for psysh, can help me for solution? or i must change config path for psysh? but how ...

Thanks,

**Comment by shaelf** [comment]
Durning deploy i catch this exception:
`Failed to clone https://github.com/bobthecow/psysh.git via https, ssh protocols, aborting.`

**Comment by GrahamCampbell** [comment]
Ping @bobthecow. Could a flag be added to tell psysh to not write to the disk?

**Comment by nejtr0n** [comment]
Same issue. Or add config option to readjust pysh write directory to another then .config/psysh

**Comment by driesvints** [comment]
Heya, this seems to be a problem with psysh and not Tinker. Check out https://github.com/bobthecow/psysh/issues/382 and perhaps try to open a new issue on their repo. Thanks!
