### ISSUE TITLE
Error while migrating from Laravel tinker console

### ISSUE THREAD

**Issue by ajthinking** [laravel/tinker#37]
- Laravel Version: 5.5.33
- PHP Version: 7.1.10
- Database Driver & Version: sqlite/postgres tested

While this works fine

    Route::get('/', function () {
        \Artisan::call('migrate:fresh');
        return "ok";
    });

Running

    \Artisan::call('migrate:fresh');
    \Artisan::call('migrate');
    ....

in tinker console results in all kinds of errors. 

Steps to reproduce and clues as described here: https://stackoverflow.com/questions/48527840/error-while-migrating-from-laravel-tinker-console-sqlite

**Comment by driesvints** [comment]
This is because `migrate:fresh` isn't in the whitelist. Tinker maintains a whitelist for "safe" commands to be used with the shell: https://github.com/laravel/tinker/blob/master/src/Console/TinkerCommand.php#L19

**Comment by driesvints** [comment]
Just sent in a PR which should document how you can add commands to the Tinker shell. So you can actually add `migrate:fresh` etc if you want: https://github.com/laravel/tinker/pull/57
