### ISSUE TITLE
Termcap issue while inside an interactive terminal in docker

### ISSUE THREAD

**Issue by jrgilman** [laravel/tinker#38]
I'm not exactly familiar with this issue, but I was on the ##linux channel on freenode trying to figure out what was causing it and the people there recommended that I bring this up as an issue.

The problem (seems to) only happens when inside of a docker container (docker exec -it XXX /bin/bash). Here is a gif of the problem: https://imgur.com/a/OCZ86

**Comment by GrahamCampbell** [comment]
This looks like an issue with psysh, or its supporting extensions. Please feel free to raise an issue on https://github.com/bobthecow/psysh.

**Comment by jrgilman** [comment]
@GrahamCampbell thanks for the direction. I've posted this issue in there.
