### ISSUE TITLE
Call to undefined function Laravel\Tinker\config_path() in 1.0.4

### ISSUE THREAD

**Issue by tomeh** [laravel/tinker#41]
I get the following error in Lumen since upgrading to 1.0.4

Call to undefined function Laravel\Tinker\config_path() 

I can work around it by adding a global config_path() function into my Lumen project but thought I would flag it up.

**Comment by GrahamCampbell** [comment]
I've fixed this up. It'll be available in the next release.

**Comment by goodevilgenius** [comment]
Any idea when this release will happen? I'd rather not lock my version to 1.0.3, or use any ugly workarounds.
