### ISSUE TITLE
Output (result) not given upon submitting a code line

### ISSUE THREAD

**Issue by cookiedumper** [laravel/tinker#43]
Not sure if it has to do with a recent Tinker update, but currently upon submitting a line (pressing Enter),  the result, or PHP output, is not shown.

Example (no result is being outputted after line is run)

    Psy Shell v0.8.16 (PHP 7.2.4 — cli) by Justin Hileman
    >>> my_func()
    >>> 

Expected (note the "bool(false)" part which is the PHP result/output)

    Psy Shell v0.8.16 (PHP 7.2.4 — cli) by Justin Hileman
    >>> my_func()
    bool(false)
    >>> 

Am I missing something? Is there a setting I need to update?

**Comment by bobthecow** [comment]
What is the value of `$_` after running `my_func()`? what is the output of `var_dump(my_func())`?

**Comment by GrahamCampbell** [comment]
Closing due to no response. Please feel free to raise an issue on https://github.com/bobthecow/psysh.
