### ISSUE TITLE
Can we have a --database flag to change database running tinker?

### ISSUE THREAD

**Issue by zakriyarahman** [laravel/tinker#51]

**Comment by StanAngeloff** [comment]
If you are running a Laravel application, you can try overriding the `DB_DATABASE` environment (Linux/Mac):

```
env DB_DATABASE=your-database-name php artisan tinker
```

This works because the [database configuration](https://github.com/laravel/laravel/blob/5.4/config/database.php#L46) pulls parameters from the environment.

**Comment by shrft** [comment]
you can specify environment too.
php artisan tinker --env=testing
