### ISSUE TITLE
tinker broken in the docker container, always show error: ErrorException with message 'stream_select(): unable to select [4]: Interrupted system call (max_fd=13)

### ISSUE THREAD

**Issue by Barbery** [laravel/tinker#52]
tinker is my dev environment is ok, but in the pro server, tinker always show error, no matter what command I input.
I have no idea, why the tinker is broken...anyone can me how to solve the problem?

![image](https://user-images.githubusercontent.com/2239529/44728907-2433c880-ab10-11e8-9e80-e059bd1440b0.png)

**Comment by GrahamCampbell** [comment]
Ping @bobthecow. Have you seen this sort of thing before perhaps?

**Comment by driesvints** [comment]
Tink it's best to just open an issue at their repo. As you can see there have been some issues about this in the past: https://github.com/bobthecow/psysh/issues?q=is%3Aissue+stream_select+is%3Aclosed

**Comment by bobthecow** [comment]
This issue [was fixed in PsySH v0.9.5](https://github.com/bobthecow/psysh/releases/tag/v0.9.5). Please update and you'll get the fix :)
