### ISSUE TITLE
SomeClass::class doesn't return fully qualified class name when class is aliased

### ISSUE THREAD

**Issue by vincemukiiri** [laravel/tinker#64]
If I have a class `App\User` and I type `User::class` in the artisan console, it first outputs `[!] Aliasing 'User' to 'App\User' for this Tinker session.` then returns `User` instead of `App\User`. 

This leads to unexpected behaviour in certain situations in tinker like when authorizing using policies `$user->can('create', User::class)` will always return `false`

**Comment by driesvints** [comment]
This is unfortunately how it works. You could use the full namespace or use the alias blacklist to prevent classes from being aliased: https://laravel.com/docs/5.7/artisan#tinker

**Comment by brysonreece** [comment]
Wouldn't this still be considered unexpected behavior? If the output to the user is that the short class name is aliased to the fully qualified class name, then the behavior of Tinker should behave such that it was indeed aliased.

What's the point in aliasing one value to another if the original value doesn't return the data it was mapped to?

**Comment by driesvints** [comment]
@brysonreece because aliasing wasn't meant to be used in combination with a full app lifecycle. If you want to run code from your app itself inside Tinker then you'd best use the full namespace.

Aliasing was meant to do some quick data retrieval, etc by just using the class name.

**Comment by brysonreece** [comment]
I understand, however the larger issue is that it is still unexpected behavior that conflicts with what the user is being told. Can the message at least be amended to reflect that better or at least be documented somewhere?

**Comment by brysonreece** [comment]
Plus it's not hard to encounter this issue without requiring interaction of a full app lifecycle.

**Comment by driesvints** [comment]
@brysonreece I'm not sure how the message can be more clear. It's already pretty clear what it means to me.

**Comment by brysonreece** [comment]
It may be a matter of semantics but I think it's easy to misinterpret "how" the requested class is aliased to the fully qualified class name. Aliasing is usually assumed that one value maps to another, like the user is being informed of. However when the value is requested again, in this case, it's not returning what they were informed it was actually "aliased" to, which leads to unexpected behavior.

**Comment by driesvints** [comment]
@brysonreece maybe a note to the docs? Feel free to send in a PR if you want to.

**Comment by Whizboy-Arnold** [comment]
hello to have the thing return the full class please import first, if in your code

otherwise  in artisan alias manually like
 use App\Models\User as AliasUser;
>>> AliasUser::class; ///gives the correct` App\Models\User`    instead of  `User` as if you just do User::class, this is as seems tinker aliases for you it only does so when you use the class not just when you want to echo the class.
consider writing say in your code 
`echo User::class; ` without first importing User
it will echo just fine without any errors but it will just echo 'User' while what you want is App\Models\User 
usually this is important in mapping polymorphic relationships
so correct use of it to give fully qualified name would rather be:
``` 
use App\Models\User;
echo User::class;
```

its more of a php issue than a laravel as php ideally should not just return the class name you give it when you have not imported it.
