### ISSUE TITLE
Tinker not updating

### ISSUE THREAD

**Issue by mrcat323** [laravel/tinker#71]
- Tinker Version: **0.9.9**
- Laravel Version: **5.7.26**
- PHP Version: **7.2.12**

### Description:
When I try to check out my data binded with eloquent relations, tinker cannot update the models, that's why, I gotta quit from it, clear cache and again run it, re-run what I ran before, 

### Before
![Before](https://user-images.githubusercontent.com/23054662/61949006-e4e15680-afc2-11e9-93aa-3bd99915f5f4.png)

### After
It's even not working after clearing the cache. I'm using **one-to-one** relation

![After](https://user-images.githubusercontent.com/23054662/61949250-9bddd200-afc3-11e9-8259-cfe88f4609b9.png)
![After 2](https://user-images.githubusercontent.com/23054662/61949319-eeb78980-afc3-11e9-8df5-53a047321d1b.png)

I've been testing it with just tinker, but without tinker everything works perfectly

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
