### ISSUE TITLE
Whitelist vendor classes for aliasing

### ISSUE THREAD

**Issue by jasonvarga** [laravel/tinker#76]
I'm frequently using Tinker to deal with classes from a package, but the aliasing doesn't happen for classes within `vendor`.

How about config array that whitelists some classes (and/or namespaces).

```
'alias' => [
   'Statamic\Entries\Entry',
]
```

I'm happy to PR this myself, but just wanted to ask before doing so.

**Comment by driesvints** [comment]
Yeah could be cool I think 👍

**Comment by zagreusinoz** [comment]
We used to be able to do this with Tinx, however that package is now deprecated so would be great for this to be part of Tinker.

**Comment by driesvints** [comment]
@zagreusinoz feel free to send in a pr
