### ISSUE TITLE
Is there a tool like tinker without laravel framework. 

### ISSUE THREAD

**Issue by qshuai** [laravel/tinker#92]
`tinker` is awesome! But I am working on golang, so I am looking for a similar tool for my workspace.

**Comment by driesvints** [comment]
yeah, it's based on Psysh: https://github.com/bobthecow/psysh

**Comment by driesvints** [comment]
I'm sorry, that wasn't a real answer to your question. I don't know if there's a similar tool for Go, sorry.

**Comment by GrahamCampbell** [comment]
Yeh, there is. https://github.com/motemen/gore is probably pretty close.
