### ISSUE TITLE
Attempting to get helpers documentation failed, like dock head.

### ISSUE THREAD

**Issue by corsicanec82** [laravel/tinker#99]
- Tinker Version: 2.4.0
- Laravel Version: 7.5.2
- PHP Version: 7.4.4
- Database Driver & Version:

### Description:
An attempt to get documentation, like dock head, in the tinker results in the following error: TypeError: Argument 1 passed to Symfony/Component/Console/Formatter/OutputFormatter::escape() must be of the type string, null given

### Steps To Reproduce:
```sh
$ php artisan tinker
Psy Shell v0.10.3 (PHP 7.4.4 — cli) by Justin Hileman
>>> doc head
TypeError: Argument 1 passed to Symfony/Component/Console/Formatter/OutputFormatter::escape() must be of the type string, null given
>>> doc last
TypeError: Argument 1 passed to Symfony/Component/Console/Formatter/OutputFormatter::escape() must be of the type string, null given
>>> doc count
function count($var, $mode = unknown)
...
works correctly
...
```

**Comment by driesvints** [comment]
Seems to be a bug with psysh. Graham has already openend an issue.

**Comment by GrahamCampbell** [comment]
This will be fixed by https://github.com/bobthecow/psysh/pull/628.

**Comment by corsicanec82** [comment]
Thanks. I will wait for fixes.
